# Generated by Django 2.0 on 2019-04-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_section_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ordenanza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.Post', verbose_name='Post'),
        ),
    ]
